### ISSUE TITLE
Using Keyboard shortcuts to adjust the selection box

### ISSUE THREAD

**Issue by webriprob** [yuxshao/ptcollab#12]
When working with small note values it may be beneficial to be able to use keyboard shortcuts to adjust the selection box

For example the keyboard shortcuts could be as follows:
**Shift + Left Arrow Key:** Moves the left bound one snap unit left
**Ctrl + Shift + Right Arrow Key:** Moves the left bound one snap unit right
**Shift + Right Arrow Key:** Moves the right bound one snap unit right
**Ctrl + Shift + Left Arrow Key:** Moves the right bound one snap unit left

**Comment by yuxshao** [comment]
Done, LMK if there are any issues.
