### ISSUE TITLE
Add an easier way to toggle "preview with all voices"

### ISSUE THREAD

**Issue by webriprob** [yuxshao/ptcollab#13]
I'm not sure how useful this would be to anyone else, but I would find it nice to have a way to toggle the "preview with all voices" in  an easier to reach spot due to the fact that when working on a song there are may times that you only want to hear the melody you're writing and many other times where you want to hear the full harmonies. Just the option isolated in the options dropdown menu would probably be fine or a checkmark box somewhere on the main panel, Either implementation would be convenient enough.

I don't know how complicated a feature like "preview with unmuted/selected units" would be to implement, but I could see me using a feature like that a lot as well.

**Comment by yuxshao** [comment]
This is a good idea, will slate for next release!

**Comment by yuxshao** [comment]
Added Ctrl+P as a shortcut for this. LMK if there are any issues.
