### ISSUE TITLE
Echo and Overdrive fields allow for the input of negative group numbers

### ISSUE THREAD

**Issue by EwanGreen4** [yuxshao/ptcollab#17]
Title is self-explanatory.
![image](https://user-images.githubusercontent.com/36348486/133870352-12ad6da2-6c9f-4be4-ab4a-de54da292051.png)
![image](https://user-images.githubusercontent.com/36348486/133870358-66d40f46-deee-4acd-b879-52e929ec91aa.png)

**Comment by yuxshao** [comment]
should be fixed with 0.4.3, thanks for the report
