### ISSUE TITLE
macOS build changes

### ISSUE THREAD

**Issue by wongjustin99** [yuxshao/ptcollab#2]
Creating this as a placeholder for a PR I'm working on. 

- [ ] Statically link libvorbis/libogg
- [ ] Statically link QT

**Comment by yuxshao** [comment]
Hey, thanks for doing this, and sorry for the late response! Let me know if there's anything I can do to help.

**Comment by yuxshao** [comment]
Sure, I wasn't sure if there was something else that was missing. Feel free to open another issue if something comes up!
