### ISSUE TITLE
Feature request: 32bit windows releases.

### ISSUE THREAD

**Issue by pachuco** [yuxshao/ptcollab#27]
Requesting 32 bit windows release binaries.

**Comment by yuxshao** [comment]
Hey, I don't have a good way to test building 32bit sadly so I'm not sure how quickly I can get to this. I have plans to set up some build scripts on one of these continuous deploy platforms so hopefully I can target win32 there.

**Comment by pachuco** [comment]
Maybe github Actions.

**Comment by yuxshao** [comment]
Hey this is super late, but I think I got something:
[ptcollab32.zip](https://github.com/yuxshao/ptcollab/files/7776414/ptcollab32.zip)

Would you mind giving a shot with this? OPNA2608 generously contributed C/D stuff with github actions so I'm hoping to put this into the C/D workflow too.

**Comment by yuxshao** [comment]
(Closing for now, but if there's still a problem let us know / reopen)
