### ISSUE TITLE
(Linux/macOS) Various installation suggestions

### ISSUE THREAD

**Issue by OPNA2608** [yuxshao/ptcollab#3]
This applies to Linux in particular, but the other major OS' would benefit from it too: Please make the installation prefix user-defined, hard-coding them is never a good idea.

https://github.com/yuxshao/ptcollab/blob/cb670e653e707c936e5bcc862c8bfb392362fe20/src/editor.pro#L177-L180

The user / their build system manager might want to install them somewhere else, mine for example expects the project file to handle the quasi-standard `PREFIX` to designate what should be considered the root directory to place `/bin`, `/lib`, `/share/[projectname]` etc under. This path can be very different from `/opt`; in my case, `PREFIX=/nix/store/ccbbas68vlr0d52h8wda9l30rma9gzn8-ptcollab-0.3.4` will be passed to the `make` invocation. A default should of course still be supplied, which *can* be `/opt` or `/usr`.

For an example how to handle this nicely, you can check out BambooTracker's project file.

https://github.com/rerrahkr/BambooTracker/blob/9fd422431e99f6bd76ad79db7fe1b0e67cf54430/BambooTracker/BambooTracker.pro#L25-L39

https://github.com/rerrahkr/BambooTracker/blob/9fd422431e99f6bd76ad79db7fe1b0e67cf54430/BambooTracker/BambooTracker.pro#L602-L627

**Comment by yuxshao** [comment]
Hey, thanks for pointing this out! I actually hadn't paid any attention to those lines before.

Poking around a bit it seems like they were added by qtcreator by default, which is a bit surprising because I agree it looks nonstandard. I'll take a look and fix it up.

**Comment by yuxshao** [comment]
Okay, I think this should be good! Thanks for the helpful examples too. Let me know if there are any other problems.

**Comment by yuxshao** [comment]
Ah, got it. Thanks so much for this! Here I was thinking using the git version was clever, haha.

There is an icon.svg in the src directory - it's unused in the code but was what generated the mac icons. I added the sample songs to the zip after realizing that mistake too. It's still in a zip, but I'll get to fixing that and the other issues sometimes today (unless you'd be willing to take a stab?).

**Comment by yuxshao** [comment]
Haha, your version may well be crisper than the existing icon. And that sounds good, don't feel any pressure - thanks again!

**Comment by yuxshao** [comment]
All right, this should be done! Assuming I didn't misconfigure anything else...

**Comment by OPNA2608** [comment]
The 16px icon seems too small (has transparent space on some sides instead of fitting to the border) & off-center.

![grafik](https://user-images.githubusercontent.com/23431373/95960930-affa3300-0e04-11eb-91ff-589af8f029b1.png)

Aside from this, it builds, installs and works fine (offline at least, haven't tried any online kerfuffle yet). Thanks!

> Haha, your version may well be crisper than the existing icon.

Well it's a vector graphic, it can't get any crisper :stuck_out_tongue_winking_eye:

**Comment by yuxshao** [comment]
Ah, great! Glad all of that works, thanks again!

As for the small icon, it's borrowed from an older project as a favicon and was set to 15x15 so the triangle could be centred in the dark box and not have to stretch. It didn't seem distracting in the browser to me, but maybe it's distracting in another desktop view? (or maybe it's always been distracting and I've just gotten numb to it haha)

**Comment by OPNA2608** [comment]
Sorry for the late response.

The smaller icon is not a deal breaker, but I can never unsee it now xp. It just *looks* unintentional I guess.

I tested it online and everything worked as well, very nice. One of my friends on macOS was bummed because she's on 10.13 High Sierra but the build manually sets the lowest supported version to 10.14 Mojave. Out of curiosity, is there something that needs this bumped target to fix? The [default for Qt 5.15](https://doc.qt.io/qt-5/macos.html#supported-versions) is 10.13.

https://github.com/yuxshao/ptcollab/blob/4827b3e895909f02980140efd30652afe257da8e/src/editor.pro#L10

I consider the issue solved in any case, many thanks!

**Comment by yuxshao** [comment]
Great, glad it worked for the most part!

I'll revisit why it's 10.14, but my vague memory is that when it wasn't set, there a number of errors for C++17 features. But I will double check and try to fix that.
