### ISSUE TITLE
Cannot bind non-const lvalue reference of type Qcolor to an rvalue of type Qcolor

### ISSUE THREAD

**Issue by XD-chill-bro** [yuxshao/ptcollab#4]
![Screenshot from 2020-11-18 20-52-54](https://user-images.githubusercontent.com/47370335/99615108-70fd6580-29e0-11eb-8ef3-140b891e6ef4.png)

a very odd error that I've encountered multiple times

**Comment by yuxshao** [comment]
Hey, would you mind sharing your compiler version, and what version of Qt you're using? Usually issues in the past have been from this. Alternatively if you could share a paste of the full error output that may be helpful.

**Comment by XD-chill-bro** [comment]
@yuxshao  the output is as follows 

`/home/prinzeono/Desktop/Projects/ptcollabProject/ptcollab/src/main.cpp:126: error: ‘optional’ is not a member of ‘std’
../../ptcollab/src/main.cpp:126:8: error: ‘optional’ is not a member of ‘std’
  126 |   std::optional<QString> recording_file = parser.value(serverRecordOption);
      |        ^~~~~~~~
../../ptcollab/src/main.cpp:126:8: note: ‘std::optional’ is only available from C++17 onwards`

I am using the very latest QT version
