### ISSUE TITLE
Install phase on Windows should install licenses & samples

### ISSUE THREAD

**Issue by OPNA2608** [yuxshao/ptcollab#40]
https://github.com/yuxshao/ptcollab/blob/b03ba18f9e88155f1c45c81673821f5faabff154/.github/workflows/ci.yml#L191-L195

These install rules

https://github.com/yuxshao/ptcollab/blob/b03ba18f9e88155f1c45c81673821f5faabff154/src/editor.pro#L296-L306

are currently gated behind a `unix`. I think it makes sense to install them no matter what platform we're on, albeit with a different path on Windows (where FHS is not a thing and having everything smushed into one place is preferred), similar to what's done here:

https://github.com/yuxshao/ptcollab/blob/b03ba18f9e88155f1c45c81673821f5faabff154/src/editor.pro#L259-L267

---

For inspiration from BambooTracker:
https://github.com/BambooTracker/BambooTracker/blob/ad82460c598390ded7ea64d119b5f98c4be15027/data/data.pro
https://github.com/BambooTracker/BambooTracker/blob/ad82460c598390ded7ea64d119b5f98c4be15027/qmake/variables.pri#L1-L19

**Comment by yuxshao** [comment]
Thanks -- see if anything looks suspicious to you here: https://github.com/yuxshao/ptcollab/pull/41
