### ISSUE TITLE
cannot bind non-const lvalue reference of type ‘QChar&’ to an rvalue of type ‘QChar’

### ISSUE THREAD

**Issue by XD-chill-bro** [yuxshao/ptcollab#5]
![Screenshot from 2020-11-20 16-09-27](https://user-images.githubusercontent.com/47370335/99854824-2d733a80-2b4b-11eb-82d6-b9dd1d50c729.png)
Full output of error:

//Desktop/Projects/ptcollabProject/ptcollab/src/protocol/RemoteAction.h:392: error: cannot bind non-const lvalue reference of type ‘QChar&’ to an rvalue of type ‘QChar’
In file included from /home/prinzeono/Qt/5.9.9/gcc_64/include/QtCore/qstring.h:48,
                 from /home/prinzeono/Qt/5.9.9/gcc_64/include/QtCore/qcoreapplication.h:44,
                 from /home/prinzeono/Qt/5.9.9/gcc_64/include/QtWidgets/qapplication.h:44,
                 from /home/prinzeono/Qt/5.9.9/gcc_64/include/QtWidgets/QApplication:1,
                 from ../../ptcollab/src/main.cpp:1:
/home/prinzeono/Qt/5.9.9/gcc_64/include/QtCore/qchar.h:599:28: note: candidate: ‘QDataStream& operator>>(QDataStream&, QChar&)’ <near match>
  599 | Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QChar &);
      |                            ^~~~~~~~
/home/prinzeono/Qt/5.9.9/gcc_64/include/QtCore/qchar.h:599:28: note:   conversion of argument 2 would be ill-formed:
In file included from ../../ptcollab/src/network/ServerSession.h:9,
                 from ../../ptcollab/src/network/BroadcastServer.h:10,
                 from ../../ptcollab/src/editor/EditorWindow.h:18,
                 from ../../ptcollab/src/main.cpp:7:
../../ptcollab/src/protocol/RemoteAction.h:392:11: error: cannot bind non-const lvalue reference of type ‘QChar&’ to an rvalue of type ‘QChar’
  392 |   in >> a.flag >> a.set;
      |         ~~^~~~

**Comment by yuxshao** [comment]
Hey! It looks like from the error you're using Qt 5.9.9 which is older than the minimum required as mentioned in the readme (5.15) -- could you try updating and try again?

**Comment by XD-chill-bro** [comment]
@yuxshao still getting the same error after updating to the latest version of qt

**Comment by XD-chill-bro** [comment]
[Output.txt](https://github.com/yuxshao/ptcollab/files/5580899/Output.txt)

Here is the output you asked for

**Comment by XD-chill-bro** [comment]
Problem is fixed due to project and editor version mismatch
