### ISSUE TITLE
Detect RtMidi via pkg-config

### ISSUE THREAD

**Issue by OPNA2608** [yuxshao/ptcollab#8]
https://github.com/yuxshao/ptcollab/blob/7783fcee695793bae12ca93a101dad17aaea818f/src/editor.pro#L8-L10
https://github.com/yuxshao/ptcollab/blob/7783fcee695793bae12ca93a101dad17aaea818f/src/editor.pro#L184-L185

You can use `pkg-config` (added compile-time dependency) [via Qmake](https://doc.qt.io/qt-5/qmake-project-files.html#configuration-features) to add the include paths, library paths and linker arguments for RtMidi instead. This doesn't rely on a hardcoded path like `/usr/include/rtmidi` and library name like `-lrtmidi`.

```qmake
CONFIG += link_pkgconfig
PKGCONFIG += rtmidi
```

**Comment by yuxshao** [comment]
Ahhh wow I had no idea this existed. Thanks so much! I'll get to adding some time soon(TM).

**Comment by yuxshao** [comment]
Hey, sorry for the super late response! I wasn't able to get this to work on windows / mac but hopefully the existing changes make it work in other environments. LMK if anything looks weird. Thanks again.

**Comment by OPNA2608** [comment]
Better dependency tests were implemented in #11, closing.
