### ISSUE TITLE
Unable to render all units separately for a certain file

### ISSUE THREAD

**Issue by etoubleh** [yuxshao/ptcollab#94]
https://battleofthebits.org/arena/Entry/in+full+bloom/53214/
I'm trying to use ptcollab to separately render all the units for this song, and it's able to render all the units from 0 to 17 with no issues, but when it gets to unit 18, it stops rendering and gives me a pop-up message saying
```
Could not render
Could not open file for rendering
```

**Comment by EwanGreen4** [comment]
It's the `:` in the unit name.

**Comment by EwanGreen4** [comment]
#95

**Comment by yuxshao** [comment]
Thanks ewan for the fix! (The next release may not be for some time so in the meantime you can probably rename the unit to get the export to work)
